# Generated by Django 4.2.2 on 2023-06-26 10:27

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("variant", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("WAITING", "waiting"),
                            ("PREAUTH", "preauth"),
                            ("CONFIRMED", "confirmed"),
                            ("REJECTED", "rejected"),
                            ("REFUNDED", "refunded"),
                            ("ERROR", "error"),
                            ("INPUT", "input"),
                        ],
                        default="WAITING",
                        max_length=255,
                    ),
                ),
                (
                    "fraud_status",
                    models.CharField(
                        choices=[
                            ("UNKNOWN", "unknown"),
                            ("ACCEPT", "accept"),
                            ("REJECT", "reject"),
                            ("REVIEW", "review"),
                        ],
                        default="UNKNOWN",
                        max_length=10,
                        verbose_name="fraud check",
                    ),
                ),
                ("fraud_message", models.TextField(blank=True, default="")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("transaction_id", models.CharField(blank=True, max_length=255)),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("CAD", "cad"),
                            ("USD", "usd"),
                            ("EUR", "eur"),
                            ("GBP", "gbp"),
                            ("AUD", "aud"),
                            ("JPY", "jpy"),
                            ("CHF", "chf"),
                            ("HKD", "hkd"),
                            ("NZD", "nzd"),
                            ("SGD", "sgd"),
                            ("SEK", "sek"),
                            ("DKK", "dkk"),
                            ("NOK", "nok"),
                            ("MXN", "mxn"),
                            ("BRL", "brl"),
                            ("MYR", "myr"),
                            ("PHP", "php"),
                            ("THB", "thb"),
                            ("IDR", "idr"),
                            ("TRY", "try"),
                            ("INR", "inr"),
                            ("RUB", "rub"),
                            ("ILS", "ils"),
                            ("SAR", "sar"),
                            ("AED", "aed"),
                            ("QAR", "qar"),
                            ("KWD", "kwd"),
                            ("BHD", "bhd"),
                            ("OMR", "omr"),
                            ("EGP", "egp"),
                            ("NGN", "ngn"),
                        ],
                        default="USD",
                        max_length=10,
                        verbose_name="Currency",
                    ),
                ),
                ("total", models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ("delivery", models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ("tax", models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ("description", models.TextField(blank=True, default="")),
                ("billing_first_name", models.CharField(blank=True, max_length=256)),
                ("billing_last_name", models.CharField(blank=True, max_length=256)),
                ("billing_address_1", models.CharField(blank=True, max_length=256)),
                ("billing_address_2", models.CharField(blank=True, max_length=256)),
                ("billing_city", models.CharField(blank=True, max_length=256)),
                ("billing_postcode", models.CharField(blank=True, max_length=256)),
                ("billing_country_code", models.CharField(blank=True, max_length=2)),
                ("billing_country_area", models.CharField(blank=True, max_length=256)),
                ("billing_email", models.EmailField(blank=True, max_length=254)),
                (
                    "billing_phone",
                    phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
                ),
                ("customer_ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("extra_data", models.JSONField(default=dict)),
                ("message", models.TextField(blank=True, default="")),
                ("token", models.CharField(blank=True, default="", max_length=36)),
                ("captured_amount", models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
            ],
            options={
                "db_table": "payment",
            },
        ),
    ]
